name: Snake Game from GitHub Contributions

on:
  schedule:
    - cron: '0 * * * *'  # Mettre à jour l'animation toutes les heures
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest  # Ce sera mis à jour vers ubuntu-24.04 à l'avenir

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate snake game from GitHub contributions grid
      uses: Platane/snk@v3.0.0
      with:
        github_user_name: 'Azox95'  # Remplace par ton nom d'utilisateur GitHub

    - name: Commit and push the generated snake animation
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add output/github-contribution-grid-snake.svg
        git commit -m "Update snake animation"
        git push https://${{ secrets.GH_TOKEN }}@github.com/Azox95/Azox95.git HEAD:main
