name: Update Snake

on:
  schedule:
    - cron: '0 0 * * *' # Exécute tous les jours à minuit

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2.0.0
        with:
          github_user: 'Azox95' # Remplacez par votre nom d'utilisateur GitHub
          output: output/github-contribution-grid-snake.gif # Emplacement du gif généré

      - name: Commit and Push
        run: |
          git add output/github-contribution-grid-snake.gif
          git commit -m "Update snake" || echo "No changes to commit"
          git push
