name: Generate Snake Game

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v2

      - name: Générer le Snake Game
        uses: Platane/snk@v2
        with:
          github_user_name: Azox95
          outputs: dist/snake.svg
