name: Update Snake

on:
  schedule:
    - cron: '0 0 * * *' # Change le temps d'exécution selon vos préférences

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2.0.0
        with:
          github_user: 'Azox95'
          # Ajoutez d'autres options si nécessaire

      - name: Commit and Push
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add .
          git commit -m "Update snake"
          git push
