name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Exécute tous les jours à minuit
  workflow_dispatch:  # Permet d'exécuter le workflow manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Vérifie le code du dépôt
      - name: Checkout the repository
        uses: actions/checkout@v2

      # 2. Génère l'animation Snake
      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: ${{ github.repository_owner }}  # Utilise le nom d'utilisateur GitHub
          outputs: output/snake.svg  # Indique où sauvegarder le fichier

      # 3. Ajouter et committer le fichier généré
      - name: Commit and push the generated snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions  # Nom de l'auteur du commit
          author_email: github-actions@github.com  # Email de l'auteur
          message: "Update snake animation"  # Message du commit
          add: "output/snake.svg"  # Indique le fichier à ajouter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utilise le token GitHub pour l'authentification
